// bits/stdc++.h
#ifndef _GLIBCXX_NO_ASSERT
#include <cassert>
#endif
#include <cctype>
#include <cerrno>
#include <cfloat>
#include <ciso646>
#include <climits>
#include <clocale>
#include <cmath>
#include <csetjmp>
#include <csignal>
#include <cstdarg>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <cwchar>
#include <cwctype>
#include <iostream>
#include <iomanip>
#include <ios>
#include <istream>
#include <ostream>
#include <sstream>
#include <streambuf>
#include <string>
#include <vector>
#include <list>
#include <deque>
#include <queue>
#include <stack>
#include <map>
#include <set>
#include <bitset>
#include <functional>
#include <utility>
#include <limits>
#include <algorithm>
#include <iterator>
#include <memory>
#include <new>
#include <typeinfo>
#include <exception>
#include <stdexcept>
#include <cassert>
#include <locale>
#include <climits>
#include <cfloat>
#include <cctype>
#include <cwchar>
#include <cwctype>
#include <complex>
